server:
  port: 8080

spring:
  datasource:
    username: root
    password: //填上自己的数据库密码
    url: jdbc:mysql://localhost:3306/jd?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/myjd/mapper/*.xml
  type-aliases-package: org.lanqiao.myjd.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        myjd :
          mapper: debug